In [6]:
# group project 1 
!pip install us 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
import gmaps
from us import states
!pip install uszipcode

from uszipcode import SearchEngine
from uszipcode import Zipcode as SimpleZipcode

# Census & gmaps API Keys
import sys
sys.path.append('../')
from config import census_api_key
from config import gkey

# Configure gmaps
gmaps.configure(api_key=gkey)

c = Census(census_api_key, year=2015)

# Configure gmaps

Requirement already satisfied: us in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (1.0.0)
Requirement already satisfied: jellyfish==0.5.6 in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from us) (0.5.6)
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied: uszipcode in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (0.2.2)
Requirement already satisfied: pathlib-mate in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from uszipcode) (0.0.14)
Requirement already satisfied: requests in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from uszipcode) (2.19.1)
Requirement already satisfied: sqlalchemy in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from uszipcode) (1.2.11)
Requirement already satisfied: attrs in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from uszipcode) (18.2.0)
Requirement already satisfied: six in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from pathlib-mate->uszipcode) (1.11.0)
Requirement already satisfied: autopep8 in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from pathlib-mate->uszipcode) (1.4.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from requests->uszipcode) (2018.8.24)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from requests->uszipcode) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from requests->uszipcode) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from requests->uszipcode) (2.7)
Requirement already satisfied: pycodestyle>=2.4.0 in /Users/SLayachi/anaconda3/lib/python3.7/site-packages (from autopep8->pathlib-mate->uszipcode) (2.4.0)
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [7]:
zipcodes_pd = pd.read_csv("../Resources/zipcode.csv")
zipcodes_pd.head()

   ZIP        LAT        LNG
0  601  18.180555 -66.749961
1  602  18.361945 -67.175597
2  603  18.455183 -67.119887
3  606  18.158345 -66.932911
4  610  18.295366 -67.125135

In [12]:

census_pd = pd.DataFrame(census_data)
census_data = c.acs5.get(("B01003_001E", "B23025_005E"), {
                         'for': 'zip code tabulation area:*'})

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B23025_005E": "Unemployment Count",
                                      "zip code tabulation area": "Zipcode"})

# Add in Employment Rate (Employment Count / Population)
census_pd["Unemployment Rate"] = 100 * \
    census_pd["Unemployment Count"].astype(
        int) / census_pd["Population"].astype(int)

# Final DataFrame
census_pd = census_pd[["Zipcode", "Population", "Unemployment Rate"]]

# Visualize
print(len(census_pd))
census_pd.head()

frames = [census_pd,zipcodes_pd]
census_pd= zipcodes_pd.join(census_pd, lsuffix='_df', rsuffix='_census_pd')


census_pd.head(10)

33120

,ZIP,LAT,LNG,Lat,Lng,population,health insurance,household,Zipcode,Population,Unemployment Rate
0,601,18.180555,-66.749961,,,,,,00601,17982.0,12.306751
1,602,18.361945,-67.175597,,,,,,00602,40260.0,9.456036
2,603,18.455183,-67.119887,,,,,,00603,52408.0,7.615250
3,606,18.158345,-66.932911,,,,,,00606,6331.0,2.827357
4,610,18.295366,-67.125135,,,,,,00610,28328.0,5.277464
5,612,18.402253,-66.711397,,,,,,00612,64816.0,6.442854
6,616,18.420412,-66.671979,,,,,,00616,10707.0,3.175493
7,617,18.445147,-66.559696,,,,,,00617,24793.0,4.489170
8,622,17.991245,-67.153993,,,,,,00622,7425.0,2.464646
9,623,18.083361,-67.153897,,,,,,00623,42955.0,3.433826

In [20]:
locations = census_pd[["LAT", "LNG"]].astype(float)

# Convert Poverty Rate to float and store
# HINT: be sure to handle NaN values
population = census_pd["Population"].astype(float)
unemployment = census_pd["Unemployment Rate"].astype(float)

In [22]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=unemployment, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

# Adjust heat_layer setting to help with heatmap dissipating on zoom
heat_layer.dissipating = False
heat_layer.max_intensity = 100
heat_layer.point_radius = 1

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))