In [9]:
#Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
from us import states
from pprint import pprint
# Census API Key
import sys
sys.path.append('../')
from config import census_api_key
c = Census(census_api_key, year=2016)
census_data = c.acs5.get(("NAME", "B01003_001E", "B01001_002E", "B01001_026E", "B02001_002E", "B02001_003E","B02001_004E", "B02001_005E",
                          "B02001_006E", "B02001_007E", "B02001_008E", "B03002_012E", "B08013_001E", "B08012_001E", "B15003_001E",
                          "B15003_002E", "B15003_003E", "B15003_004E", "B15003_005E", "B15003_006E", "B15003_007E", "B15003_008E",
                          "B15003_009E", "B15003_010E", "B15003_011E", "B15003_012E", "B15003_013E", "B15003_014E", "B15003_015E",
                          "B15003_016E", "B15003_017E", "B15003_018E", "B15003_019E", "B15003_020E", "B15003_021E", "B15003_022E",
                          "B15003_023E", "B15003_024E", "B15003_025E", "B17001_001E", "B17001_002E", "B18135_001E", "B18135_003E", 
                          "B18135_014E", "B18135_025E", "B19001_001E", "B19013_001E", "B19055_002E", "B19056_002E", "B19057_002E",
                          "B19001_002E", "B19001_003E", "B19001_004E", "B19001_005E", "B19001_006E", "B19001_007E", "B19001_008E",
                          "B19001_009E", "B19001_010E", "B19001_011E", "B19001_012E", "B19001_013E", "B19001_014E", "B19001_015E",
                          "B19001_016E", "B19001_017E", "B23025_003E", "B23025_005E", "B25002_001E", "B25002_002E", "B25004_001E",
                          "B25043_007E", "B25043_016E", "B27010_017E", "B27010_033E", "B27010_050E", "B27010_066E"),
                         {'for': 'zip code tabulation area:*'})
census_pd = pd.DataFrame(census_data)
# pprint(census_pd)
#Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01001_002E": "Male",
                                      "B01001_026E": "Female",
                                      "B02001_002E": "White",
                                      "B02001_003E": "Black",
                                      "B02001_004E": "Indian", 
                                      "B02001_005E": "Asian",
                                      "B02001_006E": "Hawaiian",
                                      "B02001_007E": "Other Race",
                                      "B02001_008E": "Multirace",
                                      "B03002_012E": "Hispanic Origin",
                                      "B08013_001E": "Length of Commute", 
                                      "B08012_001E": "Workers over 16", 
                                      "B15003_001E": "Age Over 25",
                                      "B15003_002E": "No schooling",
                                      "B15003_003E": "Nursery school",
                                      "B15003_004E": "Kindergarten",
                                      "B15003_005E": "1st grade",
                                      "B15003_006E": "2nd grade",
                                      "B15003_007E": "3rd grade",
                                      "B15003_008E": "4th grade",
                                      "B15003_009E": "5th grade",
                                      "B15003_010E": "6th grade",
                                      "B15003_011E": "7th grade",
                                      "B15003_012E": "8th grade",
                                      "B15003_013E": "9th grade",
                                      "B15003_014E": "10th grade",
                                      "B15003_015E": "11th grade",
                                      "B15003_016E": "12th grade no diploma",
                                      "B15003_017E": "High school diploma",
                                      "B15003_018E": "GED or alter",
                                      "B15003_019E": "College less than 1 year",
                                      "B15003_020E": "Some college 1 or more years",
                                      "B15003_021E": "Associate's degree",
                                      "B15003_022E": "Bachelor's degree",
                                      "B15003_023E": "Master's degree",
                                      "B15003_024E": "Professional school",
                                      "B15003_025E": "Doctorate degree",
                                      "B17001_001E": "Poverty Universe",
                                      "B17001_002E": "Poverty Count",
                                      "B18135_001E": "Non-Instiutionalized",
                                      "B18135_003E": "Disability 1",                           
                                      "B18135_014E": "Disability 2", 
                                      "B18135_025E": "Disability 3",
                                      "B19001_001E": "Households",
                                      "B19013_001E": "Per capita",
                                      "B19055_002E": "Social Security Income", 
                                      "B19056_002E": "Supplemental Security Income",
                                      "B19057_002E": "Cash Public Assistance",
                                      "B19001_002E": "Less than $10k",
                                      "B19001_003E": "$10k", 
                                      "B19001_004E": "$15k",
                                      "B19001_005E": "$20k",
                                      "B19001_006E": "$25k",
                                      "B19001_007E": "$30k",
                                      "B19001_008E": "$35k",
                                      "B19001_009E": "$40k",
                                      "B19001_010E": "$45k",
                                      "B19001_011E": "$50k",
                                      "B19001_012E": "$60k",
                                      "B19001_013E": "$75k",
                                      "B19001_014E": "$100k",
                                      "B19001_015E": "$125k",
                                      "B19001_016E": "$150k",
                                      "B19001_017E": "$200k or more",
                                      "B23025_003E": "Civilian Labor Force", 
                                      "B23025_005E": "Unemployed Civilian",
                                      "B25002_001E": "Housing Units", 
                                      "B25002_002E": "Occupied Housing",
                                      "B25004_001E": "Vacant Housing",
                                      "B25043_007E": "No phone 1", 
                                      "B25043_016E": "No phone 2",
                                      "B27010_017E": "No HI1",
                                      "B27010_033E": "No HI2",
                                      "B27010_050E": "No HI3",
                                      "B27010_066E": "No HI4",
                                      "NAME": "Name", "zip code tabulation area": "ZIP"})
# # Add in Poverty Rate (Poverty Count / Poverty Universe) [WORKS]
# census_pd["Poverty Rate"] = 100 * \
#     census_pd["Poverty Count"].astype(
#         int) / census_pd["Poverty Universe"].astype(int)
# # Average Commuting (Length of Commute / Workers Over 16) [WORKS]
#census_pd["Average Commute"] = census_pd["Length of Commute"].astype(int) / census_pd["Workers over 16"].astype(int)
# ########################################################
# # need to decide groupings for educational attainment and 
# # then divide those groupings by "Age Over 25" to get percentage of population
# ########################################################
# # Percentage of disabled population [WORKS]
census_pd["Disability"] = census_pd["Disability 1"] + census_pd["Disability 2"] + census_pd["Disability 3"]
census_pd["Disability Rate"] = 100 * census_pd["Disability"] / census_pd["Non-Instiutionalized"]
# ## public assistance rate [DOESN'T WORK]
# #census_pd["Public Assistance"] = census_pd["Social Security Income"].astype(int) + census_pd["Supplemental Security Income"].astype(int) + ["Cash Public Assistance"].astype(int)
# # census_pd["Public Assistance Rate"] = 100 * (census_pd["Social Security Income"]
# #                                              + census_pd["Supplemental Security Income"]
# #                                              + ["Cash Public Assistance"]) / census_pd["Households"]
# ########################################################
# # need to decide groupings for income levels and 
# # then divide those groupings by "Households" to get percentage of population
# ########################################################
# # # Add in Unemployment Rate [WORKS]
census_pd["Unemployment Rate"] = 100 * \
    census_pd["Unemployed Civilian"].astype(
        int) / census_pd["Civilian Labor Force"].astype(int)
# # # Add in Vacancy Rate [WORKS]
census_pd["Vacancy Rate"] = 100 * \
    census_pd["Vacant Housing"].astype(
        int) / census_pd["Housing Units"].astype(int)
# # Add Health Insurance Rate [WORKS]
census_pd["No Health Insurance"] = census_pd["No HI1"] + census_pd["No HI2"] + census_pd["No HI3"] + census_pd["No HI4"]
census_pd["No Health Insurance Rate"] = 100 * census_pd["No Health Insurance"] / census_pd["Non-Instiutionalized"]
# # Final DataFrame
# census_pd = census_pd[["Zipcode", "over 60", "under 18", "poverty level", "Poverty Rate", "Name"]]
# Visualize
census_pd.head(20)

,Male,Female,Population,White,Black,Indian,Asian,Hawaiian,Other Race,Multirace,...,No HI3,No HI4,Name,ZIP,Disability,Disability Rate,Unemployment Rate,Vacancy Rate,No Health Insurance,No Health Insurance Rate
0,8059.0,9364.0,17423.0,15974.0,256.0,5.0,703.0,24.0,277.0,184.0,...,215.0,0.0,ZCTA5 01001,01001,2282.0,13.550264,5.209920,3.902700,607.0,3.604299
1,14536.0,15434.0,29970.0,23459.0,1711.0,140.0,3502.0,17.0,230.0,911.0,...,283.0,0.0,ZCTA5 01002,01002,2294.0,7.686637,7.725974,8.925510,1152.0,3.860072
2,5694.0,5602.0,11296.0,8698.0,660.0,30.0,1538.0,0.0,130.0,240.0,...,1.0,0.0,ZCTA5 01003,01003,202.0,1.788244,19.340784,0.000000,295.0,2.611544
3,2798.0,2430.0,5228.0,5063.0,105.0,0.0,32.0,18.0,2.0,8.0,...,32.0,0.0,ZCTA5 01005,01005,581.0,11.343225,5.120482,15.943353,46.0,0.898087
4,7224.0,7664.0,14888.0,13906.0,125.0,0.0,443.0,0.0,34.0,380.0,...,28.0,0.0,ZCTA5 01007,01007,1670.0,11.217088,6.319097,4.946637,145.0,0.973939
5,632.0,562.0,1194.0,1182.0,0.0,0.0,7.0,0.0,0.0,5.0,...,14.0,0.0,ZCTA5 01008,01008,140.0,11.725293,8.224543,18.335901,33.0,2.763819
6,116.0,121.0,237.0,237.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,0.0,ZCTA5 01009,01009,64.0,27.004219,0.000000,24.285714,14.0,5.907173
7,1901.0,1817.0,3718.0,3703.0,9.0,0.0,6.0,0.0,0.0,0.0,...,0.0,0.0,ZCTA5 01010,01010,391.0,10.516407,5.851064,9.618875,33.0,0.887574
8,848.0,675.0,1523.0,1462.0,15.0,0.0,11.0,0.0,18.0,17.0,...,10.0,0.0,ZCTA5 01011,01011,225.0,14.861295,6.152125,21.923621,102.0,6.737120
9,258.0,270.0,528.0,520.0,0.0,0.0,0.0,2.0,0.0,6.0,...,26.0,0.0,ZCTA5 01012,01012,43.0,8.143939,9.748428,28.947368,42.0,7.954545
10,11100.0,11843.0,22943.0,19344.0,808.0,28.0,524.0,0.0,1919.0,320.0,...,288.0,17.0,ZCTA5 01013,01013,3171.0,13.982098,9.559913,8.911085,654.0,2.883725
11,15155.0,15474.0,30629.0,27211.0,957.0,58.0,385.0,0.0,1207.0,811.0,...,479.0,0.0,ZCTA5 01020,01020,5077.0,16.669950,7.481237,4.593748,1070.0,3.513265
12,1182.0,1346.0,2528.0,1848.0,414.0,0.0,45.0,0.0,57.0,164.0,...,18.0,0.0,ZCTA5 01022,01022,470.0,18.710191,10.445344,9.541698,27.0,1.074841
13,466.0,552.0,1018.0,974.0,33.0,0.0,0.0,0.0,0.0,11.0,...,7.0,0.0,ZCTA5 01026,01026,104.0,10.216110,4.158790,12.835249,42.0,4.125737
14,8581.0,9291.0,17872.0,16675.0,326.0,3.0,240.0,0.0,252.0,376.0,...,283.0,4.0,ZCTA5 01027,01027,2770.0,15.499105,7.235604,5.762104,613.0,3.429946
15,7363.0,8700.0,16063.0,14485.0,981.0,26.0,328.0,0.0,39.0,204.0,...,134.0,0.0,ZCTA5 01028,01028,1993.0,12.756833,5.581724,4.459502,177.0,1.132945
16,382.0,378.0,760.0,746.0,7.0,0.0,0.0,0.0,0.0,7.0,...,35.0,0.0,ZCTA5 01029,01029,88.0,11.578947,9.513274,70.156107,64.0,8.421053
17,5611.0,5667.0,11278.0,10824.0,195.0,6.0,209.0,0.0,9.0,35.0,...,186.0,0.0,ZCTA5 01030,01030,1512.0,13.406632,3.805324,3.189862,324.0,2.872850
18,658.0,534.0,1192.0,1161.0,8.0,0.0,0.0,0.0,0.0,23.0,...,11.0,0.0,ZCTA5 01031,01031,184.0,15.436242,15.241058,20.566319,37.0,3.104027
19,254.0,336.0,590.0,586.0,0.0,0.0,4.0,0.0,0.0,0.0,...,7.0,0.0,ZCTA5 01032,01032,50.0,8.474576,5.329949,27.777778,12.0,2.033898

In [4]:
zipcodes_pd = pd.read_csv("../Resources/zipcode.csv",dtype=str)
zipcodes_pd.head()

     ZIP        LAT         LNG
0  00601  18.180555  -66.749961
1  00602  18.361945  -67.175597
2  00603  18.455183  -67.119887
3  00606  18.158345  -66.932911
4  00610  18.295366  -67.125135

In [26]:
result = pd.merge(census_pd, zipcodes_pd, on=['ZIP'])

result.head(10)

,ZIP,Age Over 25,No schooling,No schooling rate,Nursery to 4th Grade Rate,5th to 8th Grade Rate,some high school rate,high school grad rate,some college rate,Associate's degree rate,Bachelor's degree rate,graduate degree rate,LAT,LNG
0,01001,13010.0,69.0,0.530361,0.176787,1.514220,6.679477,30.030746,23.036126,10.315142,15.495772,12.221368,42.062368,-72.625754
1,01002,13301.0,212.0,1.593865,0.263138,1.029998,2.217878,12.615593,11.284866,5.217653,23.765130,42.011879,42.364061,-72.458739
2,01003,121.0,0.0,0.000000,0.000000,0.000000,24.793388,5.785124,57.024793,0.000000,2.479339,9.917355,42.389941,-72.524108
3,01005,3573.0,0.0,0.000000,0.000000,0.000000,3.050658,39.518612,20.458998,8.984047,14.133781,13.853904,42.418848,-72.106598
4,01007,9985.0,18.0,0.180270,0.120180,1.512268,5.508262,22.543816,17.726590,9.794692,21.882824,20.731097,42.27901,-72.400468
5,01008,928.0,0.0,0.000000,0.000000,1.185345,5.495690,31.788793,22.090517,10.344828,17.672414,11.422414,42.190144,-72.95435
6,01009,203.0,23.0,11.330049,0.000000,0.000000,0.000000,34.482759,33.497537,3.940887,16.748768,0.000000,42.211969,-72.341433
7,01010,2753.0,17.0,0.617508,0.000000,1.380312,4.649473,24.772975,16.890665,14.166364,21.830730,15.691972,42.128176,-72.205352
8,01011,1088.0,3.0,0.275735,0.275735,1.011029,5.974265,39.154412,22.977941,11.580882,13.327206,5.422794,42.300281,-72.968716
9,01012,385.0,2.0,0.519481,0.000000,0.779221,2.597403,31.948052,16.103896,9.350649,21.038961,17.662338,42.375425,-72.858192

In [16]:
# percentage of age over 25 with no schooling
census_pd["No schooling rate"] = 100 * census_pd["No schooling"]/census_pd["Age Over 25"]
# percentage of nursey school to 4th grade
census_pd["Nurse to 4th"] = census_pd["Kindergarten"] + census_pd["1st grade"] + census_pd["2nd grade"] + census_pd["3rd grade"] + census_pd["4th grade"]
census_pd["Nursery to 4th Grade Rate"] = 100 * census_pd["Nurse to 4th"]/census_pd["Age Over 25"]
# percentage of 5th to 8th grade
census_pd["5th to 8th"] = census_pd["5th grade"] + census_pd["6th grade"] + census_pd["7th grade"] + census_pd["8th grade"]
census_pd["5th to 8th Grade Rate"] = 100 * census_pd["5th to 8th"]/census_pd["Age Over 25"]
# percentage of some high school
census_pd["some high school"] = census_pd["9th grade"] + census_pd["10th grade"] + census_pd["11th grade"] + census_pd["12th grade no diploma"]
census_pd["some high school rate"] = 100 * census_pd["some high school"]/census_pd["Age Over 25"]
# percentage of high school graduates or equilvalent
census_pd["high school grad"] = census_pd["High school diploma"] + census_pd["GED or alter"] 
census_pd["high school grad rate"] = 100 * census_pd["high school grad"]/census_pd["Age Over 25"]
# percentage of some college
census_pd["some college"] = census_pd["College less than 1 year"] + census_pd["Some college 1 or more years"] 
census_pd["some college rate"] = 100 * census_pd["some college"]/census_pd["Age Over 25"]
# percentage of associate degree
census_pd["Associate's degree rate"] = 100 * census_pd["Associate's degree"]/census_pd["Age Over 25"]
# percentage of bachelor degree
census_pd["Bachelor's degree rate"] = 100 * census_pd["Bachelor's degree"]/census_pd["Age Over 25"]
# percentage of graduate degree
census_pd["graduate degree"] = census_pd["Master's degree"] + census_pd["Professional school"] + census_pd["Doctorate degree"]
census_pd["graduate degree rate"] = 100 * census_pd["graduate degree"]/census_pd["Age Over 25"]
# # Final DataFrame
census_pd = census_pd[["ZIP", "Age Over 25", "No schooling", "No schooling rate", "Nursery to 4th Grade Rate",
                       "5th to 8th Grade Rate", "some high school rate", "high school grad rate", "some college rate",
                      "Associate's degree rate", "Bachelor's degree rate", "graduate degree rate"]]

KeyError: '5th grade'

In [24]:
import matplotlib.pyplot as plt
from matplotlib import style
from matplotlib.axes import Axes
import seaborn as sns

sns.kdeplot(df.y)

AttributeError: 'DataFrame' object has no attribute 'split_frac'